/**
 * Builds a sample two-sheet workbook with the email_spreadsheet builder and writes it to disk
 * for a visual check. With --send it is also emailed via the ronbot Gmail account
 * (RONBOT_GMAIL_USER / RONBOT_GMAIL_APP_PASSWORD, or the GCP secrets) to
 * RONBOT_SMOKE_EMAIL_TO (default alias "ron").
 *
 *   npm run smoke:xlsx -- [output.xlsx] [--send]
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseEnv } from "dotenv";
import { resolveEmailRecipientList } from "../src/config/emailAliases.js";
import { sendReportEmail } from "../src/reports/mailer.js";
import { buildWorkbook, type WorkbookSpec } from "../src/reports/xlsx.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ronbotMcpRoot = path.resolve(__dirname, "..");
const shellEnvKeys = new Set(Object.keys(process.env));
for (const file of [path.join(ronbotMcpRoot, "..", ".env"), path.join(ronbotMcpRoot, ".env")]) {
  if (!existsSync(file)) continue;
  for (const [key, value] of Object.entries(parseEnv(readFileSync(file)))) {
    if (!shellEnvKeys.has(key)) process.env[key] = value;
  }
}

const args = process.argv.slice(2);
const send = args.includes("--send");
const output = args.find((a) => !a.startsWith("--")) ?? path.join(tmpdir(), "ronbot-smoke.xlsx");

const spec: WorkbookSpec = {
  sheets: [
    {
      name: "CRH occupancy 2026",
      title: "CRH occupancy by month, 2026",
      subtitle: "Sample data generated by smoke-xlsx",
      columns: [
        { header: "Month", type: "text" },
        { header: "Occupancy", type: "percent" },
        { header: "Beds booked", type: "integer" },
        { header: "Revenue", type: "currency" },
        { header: "ADR", type: "currency" },
      ],
      rows: [
        ["Jan 2026", 61.4, 3420, 68212.5, 19.95],
        ["Feb 2026", 66.9, 3365, 70110.25, 20.84],
        ["Mar 2026", "72.3%", "4,012", "£91,330.10", 22.76],
        ["Apr 2026", 80.1, 4310, 112004, 25.99],
      ],
      totals: [2, 3],
      notes: ["Occupancy is beds booked / beds available.", "ADR = revenue / beds booked."],
    },
    {
      name: "Arrivals",
      columns: [
        { header: "Reservation", type: "text" },
        { header: "Check-in", type: "date" },
        { header: "Booked at", type: "date" },
        { header: "Nights", type: "integer" },
        { header: "Balance", type: "currency" },
      ],
      rows: [
        ["4586958844219", "2026-10-08", "2026-09-30T14:22", 3, 0],
        ["4587001234567", "2026-10-09", "2026-10-01 09:05:11", 1, 24.5],
        ["4587009999999", "2026-10-09", null, 2, null],
      ],
    },
  ],
};

const buffer = await buildWorkbook(spec);
writeFileSync(output, buffer);
console.log(`Wrote ${output} (${buffer.length} bytes)`);

if (send) {
  const to = resolveEmailRecipientList(process.env.RONBOT_SMOKE_EMAIL_TO?.trim() || "ron");
  const { messageId } = await sendReportEmail({
    to,
    subject: "Ronbot spreadsheet smoke test",
    body: "Sample workbook from ronbot-mcp scripts/smoke-xlsx.ts.",
    filename: "Ronbot spreadsheet smoke test.xlsx",
    attachment: buffer,
  });
  console.log(`Sent to ${to.join(", ")} (${messageId})`);
}
